services:
  valheim-server-friends:
    build:
      context: .
      args:
        TESTS: "false"
      dockerfile: Dockerfile
    container_name: valheim-server-friends
    volumes:
      - /home/hi-tech/valheim-server/valheim-server-friends/config:/config
      - /home/hi-tech/valheim-server/valheim-server-friends/data:/opt/valheim
    ports:
      - "2456-2458:2456-2458/udp"
      - "9003:9001/tcp"
      - "8003:80/tcp"
    env_file:
      - /home/hi-tech/valheim-server/valheim-server-friends/valheim.env
    restart: unless-stopped
    stop_grace_period: 2m

