services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: valheim-server-family
    volumes:
      - /home/hi-tech/valheim-server-family/config:/config
      - /home/hi-tech//valheim-server-family/data:/opt/valheim
    ports:
      - "2456-2458:2456-2458/udp"
      - "9001:9001/tcp"
      - "8005:80/tcp"
    env_file:
      - /home/hi-tech/valheim-server-family/valheim.env
   restart: always
    stop_grace_period: 2m

